const ITEMS=window.HOLIDAY_ITEMS,state={type:"All",area:"All",search:"",view:"list",gps:null};
const cache=JSON.parse(localStorage.getItem("holidayapp_coords_v1")||"{}");
let map,layer,myMarker,busy=false,generation=0,resizeObserver=null;
const $=id=>document.getElementById(id),E={search:$("search"),area:$("area"),types:$("types"),listBtn:$("listBtn"),mapBtn:$("mapBtn"),gpsBtn:$("gpsBtn"),gpsStatus:$("gpsStatus"),clearBtn:$("clearBtn"),count:$("count"),cards:$("cards"),listView:$("listView"),mapView:$("mapView"),mapStatus:$("mapStatus")};
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const key=i=>i.name+"|"+i.location;
function rows(){const q=state.search.trim().toLowerCase();return ITEMS.filter(i=>(state.type==="All"||i.type===state.type)&&(state.area==="All"||i.area===state.area)&&(!q||[i.name,i.location,i.area,i.type,i.description].join(" ").toLowerCase().includes(q)))}
const maps=i=>"https://www.google.com/maps?q="+encodeURIComponent(i.location);
const directions=i=>"https://www.google.com/maps/dir/?api=1&destination="+encodeURIComponent(i.location)+"&travelmode=driving";
function km(a,b){const R=6371,r=x=>x*Math.PI/180,d1=r(b.lat-a.lat),d2=r(b.lng-a.lng),q=Math.sin(d1/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function dist(i){if(!state.gps)return"";const c=cache[key(i)];if(!c)return"Distance pending map location";const m=km(state.gps,c)*.621371;return(m<10?m.toFixed(1):Math.round(m))+" miles away"}
function render(){const r=rows();E.count.textContent=`${r.length} of ${ITEMS.length} places`;E.cards.innerHTML=r.length?r.map(i=>{const d=dist(i);return`<article class="card" data-type="${esc(i.type)}"><div class="accent"></div><div class="card-body"><h2>${esc(i.name)}</h2><div class="badges"><span class="badge">${esc(i.type)}</span><span class="badge">${esc(i.area)}</span></div><p class="desc">${esc(i.description)}</p><p class="meta">${i.visitTime?`<strong>Visit:</strong> ${esc(i.visitTime)}<br>`:""}<strong>Location:</strong> ${esc(i.location)}${d?`<br><span class="distance">${esc(d)}</span>`:""}</p><div class="actions"><a class="btn primary" target="_blank" rel="noopener" href="${esc(maps(i))}">Google Maps</a><a class="btn secondary" target="_blank" rel="noopener" href="${esc(directions(i))}">Directions</a>${i.website1?`<a class="btn" target="_blank" rel="noopener" href="${esc(i.website1)}">Website</a>`:""}${i.website2?`<a class="btn" target="_blank" rel="noopener" href="${esc(i.website2)}">More info</a>`:""}</div></div></article>`}).join(""):'<div class="card"><div class="card-body">No matching places.</div></div>'}
function initMap(){if(map)return;map=L.map("map",{zoomControl:true,preferCanvas:true}).setView([53.25,-8.05],7);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,updateWhenIdle:true,keepBuffer:4,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);layer=L.layerGroup().addTo(map);if(window.ResizeObserver){resizeObserver=new ResizeObserver(()=>{if(map&&state.view==="map")map.invalidateSize({pan:false})});resizeObserver.observe(document.getElementById("map"));}}
function stabiliseMapSize(){if(!map)return;requestAnimationFrame(()=>requestAnimationFrame(()=>{map.invalidateSize({pan:false});setTimeout(()=>map&&map.invalidateSize({pan:false}),150);setTimeout(()=>map&&map.invalidateSize({pan:false}),500)}));}
function icon(type,s){return L.divIcon({className:"",html:`<div class="pin ${type.toLowerCase()}"><span>${s}</span></div>`,iconSize:[24,24],iconAnchor:[12,24],popupAnchor:[0,-24]})}
const syms={Attraction:"★",Hotel:"H",Lunch:"L",Dinner:"D"};
function popup(i){return`<div class="popup-title">${esc(i.name)}</div><div class="popup-meta">${esc(i.type)} · ${esc(i.area)}</div><div>${esc(i.description)}</div><div class="popup-actions"><a target="_blank" rel="noopener" href="${esc(maps(i))}">Google Maps</a><a target="_blank" rel="noopener" href="${esc(directions(i))}">Directions</a></div>`}
function redraw(fit=false){if(!map)return;layer.clearLayers();const pts=[];for(const i of rows()){const c=cache[key(i)];if(!c)continue;L.marker([c.lat,c.lng],{icon:icon(i.type,syms[i.type]||"•"),title:i.name}).bindPopup(popup(i)).addTo(layer);pts.push([c.lat,c.lng])}if(state.gps){if(myMarker)myMarker.remove();myMarker=L.marker([state.gps.lat,state.gps.lng],{icon:icon("me","●"),title:"You are here"}).bindPopup("You are here").addTo(map);pts.push([state.gps.lat,state.gps.lng])}if(fit&&pts.length){map.fitBounds(pts,{padding:[30,30],maxZoom:14,animate:false});}}
async function geocode(){if(busy){generation++;return}busy=true;const g=++generation,r=rows(),missing=r.filter(i=>!cache[key(i)]);E.mapStatus.textContent=missing.length?`Locating ${missing.length} uncached place${missing.length===1?"":"s"}… The map will stay still while they load.`:`All ${r.length} filtered places are cached.`;redraw(true);for(let n=0;n<missing.length;n++){if(g!==generation)break;const i=missing[n];try{const url="https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=ie&q="+encodeURIComponent(i.name+", "+i.location);const res=await fetch(url,{headers:{Accept:"application/json"}});if(res.ok){const d=await res.json();if(d[0]){cache[key(i)]={lat:+d[0].lat,lng:+d[0].lon};localStorage.setItem("holidayapp_coords_v1",JSON.stringify(cache));redraw(false);render();}}}catch(e){console.warn("Geocode failed",i.name,e)}E.mapStatus.textContent=`Locating places… ${Math.min(n+1,missing.length)} / ${missing.length} checked. Map position is locked until complete.`;await new Promise(x=>setTimeout(x,1050))}busy=false;const left=rows().filter(i=>!cache[key(i)]).length;E.mapStatus.textContent=left?`${left} filtered place${left===1?"":"s"} could not be located automatically; the rest are shown.`:`All ${rows().length} filtered places are shown.`;redraw(true);stabiliseMapSize();render()}
function refresh(){render();if(state.view==="map"){initMap();stabiliseMapSize();redraw(true);geocode()}}
function gps(){if(!navigator.geolocation){E.gpsStatus.textContent="GPS not supported by this browser.";return}E.gpsBtn.disabled=true;E.gpsStatus.textContent="Requesting location permission…";navigator.geolocation.getCurrentPosition(p=>{state.gps={lat:p.coords.latitude,lng:p.coords.longitude};E.gpsStatus.textContent="Location enabled — distances are straight-line estimates.";E.gpsBtn.textContent="Location enabled";render();if(map){redraw(true);stabiliseMapSize()}},()=>{E.gpsBtn.disabled=false;E.gpsStatus.textContent="Location permission was blocked. Check browser/site Location permissions."},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
E.search.addEventListener("input",e=>{state.search=e.target.value;refresh()});
E.area.addEventListener("change",e=>{state.area=e.target.value;refresh()});
E.types.addEventListener("click",e=>{const b=e.target.closest("[data-type]");if(!b)return;state.type=b.dataset.type;document.querySelectorAll("[data-type]").forEach(x=>x.classList.toggle("active",x===b));refresh()});
E.listBtn.addEventListener("click",()=>{state.view="list";generation++;E.listView.classList.remove("hidden");E.mapView.classList.remove("active");E.listBtn.classList.add("active");E.mapBtn.classList.remove("active")});
E.mapBtn.addEventListener("click",()=>{state.view="map";E.listView.classList.add("hidden");E.mapView.classList.add("active");E.mapBtn.classList.add("active");E.listBtn.classList.remove("active");initMap();stabiliseMapSize();setTimeout(()=>refresh(),60)});
E.gpsBtn.addEventListener("click",gps);
E.clearBtn.addEventListener("click",()=>{state.type="All";state.area="All";state.search="";E.search.value="";E.area.value="All";document.querySelectorAll("[data-type]").forEach(x=>x.classList.toggle("active",x.dataset.type==="All"));refresh()});
window.addEventListener("resize",()=>{if(map&&state.view==="map")stabiliseMapSize()});
window.addEventListener("orientationchange",()=>{if(map&&state.view==="map")setTimeout(stabiliseMapSize,250)});
render();